/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/model.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={25.361} position={[35.228, 1.922, 24.915]} rotation={[0.046, 0.955, -0.038]} />
      <mesh geometry={nodes.Shadow_Catcher.geometry} material={materials.Shadow_catcher} position={[-0.351, -0.044, -0.471]} scale={10} opacity={[0.2]}/>
      <mesh geometry={nodes.Cottage_Free.geometry} material={materials.Cottage_FREE} />
    </group>
  )
}

useGLTF.preload('/model.glb')
